

ALTER TABLE countries ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE countries ADD COLUMN updated_at TIMESTAMP; 

ALTER TABLE cities ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE cities ADD COLUMN updated_at TIMESTAMP; 

ALTER TABLE buildings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 
ALTER TABLE buildings ADD COLUMN updated_at TIMESTAMP; 


